networks:
  app-tier:
    driver: bridge

services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

  
  cleaniam:
    image: base_host-final:latest
    environment:
      - YOUR_ENV_VAR=your_value
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    networks:
        - app-tier
    depends_on:
        - postgres
  

