using Events.Core.Events.ManagementPortal.Users;
using Identity.Core.Users;
using Marten;

namespace Identity.Application.EventHandlers.Users;

/// <summary>
/// Handles the UserDeleted event generated by ManagementPortal and deletes the corresponding user from the database.
/// </summary>
public class UserDeletedEventHandler
{
    public static async Task Handle(UserDeleted userDeleted, IDocumentSession session,
        CancellationToken cancellationToken)
    {
        session.Delete<IdentityUser>(userDeleted.Id);
        await session.SaveChangesAsync(cancellationToken);
    }
}