using Events.Core.Events.Identity;
using Mapster;
using Marten;
using Users.Core;

namespace Users.Application.EventHandlers;

/// <summary>
/// Handles the NewUserSignedUp event generated by Identity project and updates the corresponding users in the database.
/// </summary>
public class NewUserSignedUpEventHandler
{
    public static async Task Handle(NewUserSignedUp userSignedUp, IDocumentSession session,
        CancellationToken cancellationToken)
    {
        var newUser = userSignedUp.Adapt<User>();
        session.Store(newUser);
        await session.SaveChangesAsync(cancellationToken);
    }
}