using CleanIAM.Events.Core.Events.Identity;
using CleanIAM.Users.Core;
using Mapster;
using Marten;

namespace CleanIAM.Users.Application.EventHandlers;

/// <summary>
/// Handles the NewUserSignedUp event generated by CleanIAM.Identity project and updates the corresponding users in the database.
/// </summary>
public class NewUserSignedUpEventHandler
{
    public static async Task Handle(NewUserSignedUp userSignedUp, IDocumentSession session,
        CancellationToken cancellationToken)
    {
        var newUser = userSignedUp.Adapt<User>();
        session.Store(newUser);
        await session.SaveChangesAsync(cancellationToken);
    }
}